# Generated by Django 5.1.6 on 2025-02-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='code',
        ),
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
