# Generated by Django 5.1.6 on 2025-02-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_inventory_code_inventory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.IntegerField(verbose_name=1),
        ),
    ]
