# Generated by Django 5.1.6 on 2025-02-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_inventory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='img',
            field=models.TextField(default='No Image'),
            preserve_default=False,
        ),
    ]
