# Generated by Django 5.1.6 on 2025-02-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_inventory_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.IntegerField(),
        ),
    ]
